# Generated by Django 5.0 on 2023-12-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='meta_mask_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
